### ISSUE TITLE
Some work needed for Effects UI to make it dynamic

### ISSUE THREAD

**Issue by mohamedmansour** [mohamedmansour/my-hangouts-extension#11]
The effects are cut from the bottom and the pane is stretched horizontally. We would need to make the panel that pops out stretch to the image and the effects to always show.

Perhaps what we can do is when the image is clicked, it will zoom in to the screen (size of the real image), and add an effects toolbar in the bottom.

The effects toolbar could be easier to understand in  a way we have multiple effects, like how Piknic does it.

**Comment by jwill** [comment]
One thing we could do is to add

_overflow:scroll_ to the capturePreview div to make only the image scrollable about not the outer lightbox.

Another option is to default to showing the image at 50%(or some other preset) height/width based on the innerWidth and innerHeight of the outside window so that it looks more optimal.

The toolbar was a first cut at getting the features in there (pretty or not). We definitely have to tweak it because as it stands you can only set one effect at a time. For more than one you have to save the image and then apply an effect on the new one.

**Comment by mohamedmansour** [comment]
Merged @rbouajram changes to this f5966bddc0cc8551c926200365f5937279ac937f

**Comment by mohamedmansour** [comment]
closing it cause work has been done, we will now open more issues for smaller bug fixes instead.
