### ISSUE TITLE
(Feature Request) Add filters for the saved images (postprocessing)

### ISSUE THREAD

**Issue by jwill** [mohamedmansour/my-hangouts-extension#5]
This lib http://evanw.github.com/glfx.js/demo/ looks like it could be slotted in pretty easily.

It might require a popup to be surfaced to set attributes on the filter.

Could submit a patch if you'd prefer.

**Comment by mohamedmansour** [comment]
Woah, that is super cool James! What would be cool is when we "click" on the image on the gallery, it will goto edit mode, then once in edit mode we can add these filters. And when we save, we ask the user if they want to replace, or create a new one.

Hmmm should be the top priority now :)

**Comment by jwill** [comment]
I'm working on a rev1 of this.

**Comment by mohamedmansour** [comment]
Please rebase your changes to the new ones right now (lots been added so you wont conflict). Easier to reset origin/master. When your online, let me know so I can help you get upto speed quicky :)

**Comment by mohamedmansour** [comment]
I have pushed it and changed the code a bit to make it not dependent on gallery so it can be separated. Removed eval as well.  I upgraded jquery since the mouse warnings were there. And instead of refreshing the gallery, I just appended it to the DOM so you wont see a flicker.

It is excellent :) Good job, I really like it! Some stuff we need to improve is:
- The nubs are not working on the entire image, more info here #10
- We need to work more on the UI to make it fit nicely to the design #11

Other than that it is perfect :) Closing this issue since we have opened new one! Excited for the new release!
